[mypy]
strict = true
python_version = 3.11

[mypy-dxcam]
ignore_missing_imports = true

[mypy-win32cred]
ignore_missing_imports = true

[mypy-win32con]
ignore_missing_imports = true

[mypy-pywintypes]
ignore_missing_imports = true

[mypy-comtypes]
ignore_missing_imports = true

[mypy-comtypes.client]
ignore_missing_imports = true

[mypy-aiohttp]
ignore_missing_imports = true

[mypy-websockets]
ignore_missing_imports = true

[mypy-pytesseract]
ignore_missing_imports = true

[mypy-pdf2image]
ignore_missing_imports = true

[mypy-openpyxl]
ignore_missing_imports = true

[mypy-pypdf]
ignore_missing_imports = true

[mypy-pyautogui]
ignore_missing_imports = true

[mypy-win32api]
ignore_missing_imports = true
